version: '3.0'
services:
    api:
        build: .
        ports:
            - "5000:5000"

    auth:
        image: quay.io/pusher/oauth2_proxy:v6.1.1
        environment:
            - OAUTH2_PROXY_PROVIDER=oidc # https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc
            - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
            - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
            - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
            - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
            - OAUTH2_PROXY_SCOPE=openid profile email
            - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8000/oauth2/callback
            - OAUTH2_PROXY_HTTP_ADDRESS=http://:8000
            - OAUTH2_PROXY_UPSTREAMS=http://api:5000
            - OAUTH2_PROXY_COOKIE_REFRESH=60m
            - OAUTH2_PROXY_COOKIE_SECURE=false # only for development
            - OAUTH2_PROXY_EMAIL_DOMAINS=*
            - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
        ports:
            - "8000:8000" # In prod, this is served on port 443
