apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: gathering-iris
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: server
      src: "."
      ports:
        - name: http
          port: 5000
    - name: auth
      image: quay.io/pusher/oauth2_proxy:v4.1.0 # see https://pusher.github.io/oauth2_proxy/configuration
      ports:
        - name: auth-http
          port: 8000
      publicPort: auth-http
      environmentConfig:
        - environment: prod
          monitoring: true
          variables:
            OAUTH2_PROXY_COOKIE_REFRESH: "60m"
            OAUTH2_PROXY_EMAIL_DOMAINS: "*"
            OAUTH2_PROXY_HTTP_ADDRESS: "http://:8000"
            OAUTH2_PROXY_OIDC_ISSUER_URL: "https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0"
            OAUTH2_PROXY_PROVIDER: "oidc"
            OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
            OAUTH2_PROXY_UPSTREAMS: "http://server:5000"
            OAUTH2_PROXY_COOKIE_SECURE: true
          resources:
            requests:
              memory: "50Mi"
              cpu: "25m"
            limits:
              memory: "50Mi"
              cpu: "1000m"
      secrets:
        - OAUTH2_PROXY_CLIENT_ID
        - OAUTH2_PROXY_CLIENT_SECRET
        - OAUTH2_PROXY_COOKIE_SECRET
        - OAUTH2_PROXY_REDIRECT_URL
        - OAUTH2_PROXY_SCOPE
  dnsAppAlias:
    environment: prod
    component: auth
